=== YJSoft/Karybu/modules/flow/conf/flow.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.arnia.ro/qub/" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:qub="http://www.arnia.ro/qub/">

    <complexType name="formType">
    	<sequence maxOccurs="1" minOccurs="1" >
    		<sequence maxOccurs="unbounded" minOccurs="0" >
    			<element name="field" type="qub:fieldType"></element>
    		</sequence>
	    	<element name="navigation" type="qub:navigationType" minOccurs="0"></element>
    	</sequence>
    	<attribute name="id" type="string" use="required"></attribute>
    	<attribute name="filename" type="string"></attribute>
    </complexType>

    <complexType name="fieldType">
    	<attribute name="name" type="string"></attribute>
    	<attribute name="required" type="boolean"></attribute>
    </complexType>

    <complexType name="navigationType">
    	<sequence>
    		<element name="next" type="qub:directionType" maxOccurs="unbounded" minOccurs="0"></element>
    		<element name="previous" type="qub:directionType" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <complexType name="directionType">
    	<sequence>
	    	<choice>
	    		<element name="form" type="string"></element>
	    		<element name="url" type="string"></element>
	    	</choice>
	   		<element name="condition" type="string"></element>
	   	</sequence>
    </complexType>
    
    <complexType name="flowType">
    	<sequence>
    		    <element name="form" type="qub:formType" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>
    
    <element name="flow" type="qub:flowType"></element>
    
</schema>

=== YJSoft/Karybu/modules/flow/Flow/testConf.xml
<?xml version="1.0" encoding="UTF-8"?>
<qub:flow xmlns:qub="http://www.arnia.ro/qub/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.arnia.ro/qub/ ../conf/flow.xsd ">
  
  <form id="form1">
    <field name="first_name" required="true"/>
    <field name="last_name" required="true"/>
    <navigation>
      <next>
        <url>index.php?mid=flow&amp;act=dispQ1</url>
        <condition>$last_name=='Razvan'</condition>
      </next>
      <next>
        <url>index.php</url>
        <condition>$last_name==Dummy\DummyModel::standardAnswer()</condition>
      </next>
      <next>
        <form>form2</form>
        <condition>true</condition>
      </next>
      <previous>
        <url>www.google.com</url>
        <condition>true</condition>
      </previous>
    </navigation>
  </form>
    
  <form id="form2">
    <field name="city" required="true"/>
    <field name="county" required="true"/>
    <navigation>
      <next>
        <form>form3</form>
        <condition>true</condition>
      </next>
      <previous>
        <form>form1</form>
        <condition>true</condition>
      </previous>
    </navigation>
  </form>

  <form id="form3"/>


</qub:flow>
